INSERT INTO USER_ROLES (USERNAME, ROLE) VALUES ('admin', 'admin');
INSERT INTO USER_ROLES (USERNAME, ROLE) VALUES ('wuhaitao', 'doctor');
INSERT INTO USER_ROLES (USERNAME, ROLE) VALUES ('jql', 'patient');
INSERT INTO USER_ROLES (USERNAME, ROLE) VALUES ('test1', 'doctor');
INSERT INTO USER_ROLES (USERNAME, ROLE) VALUES ('test2', 'patient');
INSERT INTO USER_ROLES (USERNAME, ROLE) VALUES ('test3', 'doctor');
INSERT INTO USER_ROLES (USERNAME, ROLE) VALUES ('patient', 'patient');
INSERT INTO USER_ROLES (USERNAME, ROLE) VALUES ('doctor', 'doctor');